import random

# --- BASE DE DADOS DE INIMIGOS ---
INIMIGOS = [
    {
        "nome": "Goblin",
        "tipo": "Monstro",
        "nivel": 1,
        "hp": 30,
        "ataque": 8,
        "defesa": 2,
        "xp_recompensa": 10,
        "fraqueza": "Fogo",
        "medo": 40,
        "inteligencia": 20,
        "forca": 15,
        "destreza": 30,
    },
    {
        "nome": "Morcego Gigante",
        "tipo": "Fera",
        "nivel": 1,
        "hp": 25,
        "ataque": 10,
        "defesa": 1,
        "xp_recompensa": 8,
        "fraqueza": "Físico",
        "medo": 25,
        "inteligencia": 10,
        "forca": 10,
        "destreza": 45,
    },
    {
        "nome": "Rato Mutante",
        "tipo": "Peste",
        "nivel": 1,
        "hp": 35,
        "ataque": 6,
        "defesa": 3,
        "xp_recompensa": 12,
        "fraqueza": "Físico",
        "medo": 50,
        "inteligencia": 15,
        "forca": 20,
        "destreza": 25,
    },
    {
        "nome": "Esqueleto",
        "tipo": "Morto-Vivo",
        "nivel": 1,
        "hp": 40,
        "ataque": 5,
        "defesa": 4,
        "xp_recompensa": 15,
        "fraqueza": "Mágico",
        "medo": 0,
        "inteligencia": 5,
        "forca": 25,
        "destreza": 10,
    },
    {
        "nome": "Vespa Venenosa",
        "tipo": "Inseto",
        "nivel": 1,
        "hp": 20,
        "ataque": 12,
        "defesa": 0,
        "xp_recompensa": 7,
        "fraqueza": "Vento",
        "medo": 10,
        "inteligencia": 5,
        "forca": 5,
        "destreza": 50,
    },
    {
        "nome": "Troll",
        "tipo": "Gigante",
        "nivel": 2,
        "hp": 60,
        "ataque": 15,
        "defesa": 5,
        "xp_recompensa": 30,
        "fraqueza": "Fogo",
        "medo": 60,
        "inteligencia": 30,
        "forca": 50,
        "destreza": 15,
    },
    {
        "nome": "Guerreiro Orc",
        "tipo": "Humanoide",
        "nivel": 2,
        "hp": 50,
        "ataque": 18,
        "defesa": 4,
        "xp_recompensa": 25,
        "fraqueza": "Perfuração",
        "medo": 20,
        "inteligencia": 40,
        "forca": 45,
        "destreza": 30,
    },
    {
        "nome": "Lobo do Gelo",
        "tipo": "Fera",
        "nivel": 2,
        "hp": 45,
        "ataque": 20,
        "defesa": 3,
        "xp_recompensa": 22,
        "fraqueza": "Fogo",
        "medo": 15,
        "inteligencia": 25,
        "forca": 40,
        "destreza": 40,
    },
    {
        "nome": "Elemental de Gelo",
        "tipo": "Elemental",
        "nivel": 2,
        "hp": 70,
        "ataque": 12,
        "defesa": 6,
        "xp_recompensa": 35,
        "fraqueza": "Fogo",
        "medo": 0,
        "inteligencia": 50,
        "forca": 35,
        "destreza": 20,
    },
    {
        "nome": "Sombra",
        "tipo": "Fantasma",
        "nivel": 2,
        "hp": 30,
        "ataque": 25,
        "defesa": 0,
        "xp_recompensa": 40,
        "fraqueza": "Luz",
        "medo": 0,
        "inteligencia": 60,
        "forca": 10,
        "destreza": 60,
    },
    {
        "nome": "Lich",
        "tipo": "Morto-Vivo",
        "nivel": 3,
        "hp": 80,
        "ataque": 30,
        "defesa": 10,
        "xp_recompensa": 70,
        "fraqueza": "Luz",
        "medo": 0,
        "inteligencia": 90,
        "forca": 30,
        "destreza": 40,
    },
    {
        "nome": "Bruxa Corrompida",
        "tipo": "Mago",
        "nivel": 3,
        "hp": 65,
        "ataque": 35,
        "defesa": 5,
        "xp_recompensa": 65,
        "fraqueza": "Físico",
        "medo": 5,
        "inteligencia": 85,
        "forca": 20,
        "destreza": 50,
    },
    {
        "nome": "Gárgula",
        "tipo": "Monstro",
        "nivel": 3,
        "hp": 90,
        "ataque": 25,
        "defesa": 15,
        "xp_recompensa": 75,
        "fraqueza": "Mágico",
        "medo": 10,
        "inteligencia": 40,
        "forca": 70,
        "destreza": 35,
    },
    {
        "nome": "Guardião de Ferro",
        "tipo": "Gólem",
        "nivel": 3,
        "hp": 120,
        "ataque": 20,
        "defesa": 20,
        "xp_recompensa": 80,
        "fraqueza": "Elétrico",
        "medo": 0,
        "inteligencia": 10,
        "forca": 90,
        "destreza": 5,
    },
    {
        "nome": "Banshee",
        "tipo": "Fantasma",
        "nivel": 3,
        "hp": 50,
        "ataque": 40,
        "defesa": 0,
        "xp_recompensa": 90,
        "fraqueza": "Silêncio",
        "medo": 0,
        "inteligencia": 70,
        "forca": 5,
        "destreza": 75,
    },
]


def obter_inimigo_aleatorio(nivel):
    # Vamos filtrar os inimigos pelo nível solicitado
    inimigos_filtrados = [monstro for monstro in INIMIGOS if monstro["nivel"] == nivel]
    # Se não houver inimigos desse nível, retornamos None
    if not inimigos_filtrados:
        return random.choice(inimigos_filtrados)
    else:
        print(
            f"Aviso: Nenhum inimigo encontrado para o nível {nivel}. Usando um inimigo de nível 1."
        )
        # Retornamos um inimigo de nível 1 como padrão
        inimigos_filtrados = [monstro for monstro in INIMIGOS if monstro["nivel"] == 1]
        return random.choice(inimigos_filtrados_padrao)


# --- FIM DA BASE DE DADOS DE INIMIGOS ---
